### ISSUE TITLE
Unable to deploy with recent Gunicorn

### ISSUE THREAD

**Issue by pkese** [rvanlaar/djangorecipe#84]
In previous versions of gunicorn, the way to deploy/run gunicorn was `bin/django run_gunicorn`

In recent versions of gunicorn however, the default method of deployment is to run `gunicorn` directly from command line rather than through django management.

So is there a way to somehow generate `bin/gunicorn` as the old method is now deprecated?

Note: the documentation does indeed mention `wsgi-script
    The name of the wsgi-script that is generated. This can be useful for gunicorn.` but doesn't say how.

**Comment by reinout** [comment]
This should be fixed with release 2.0. Read the changelogs, as I've done quite some cleanup regarding options :-)

Basic idea: add `script-entrypoints = gunicorn` to your `[django]` part and you'll get a `bin/django_env_gunicorn` script that's the same as `bin/gunicorn` but with the settings env variable set.

As you were using extra-paths for instance, can you check if 2.0 works for you? I've removed some options that seemed to be unused (=only necessary when django wasn't really a proper python package). I might have removed too much :-)

Also feedback regarding changelog/readme and the naming of the bin/django_env_gunicorn (in your case it would be bin/project_env_gunicorn) script is welcome.

**Comment by andrewebdev** [comment]
thx @reinout 
Currently busy with other deadlines, but will review the new recipe and gunicorn options soon as I have the time :)

**Comment by reinout** [comment]
No hurry :-)
